apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexplane.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nexplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
