apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexplane.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexplane.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  secret-key: {{ .Values.secretKey | b64enc | quote }}
  database-url: {{ .Values.backend.env.DATABASE_URL | b64enc | quote }}
