# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2026 Nexplane, Inc.

"""
Generates revocation change requests for approved review campaigns.
One ChangeRequest per revoked ReviewEntry, using the appropriate connector action.
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.review_campaign import ReviewCampaign, ReviewEntry
from app.models.change_request import ChangeRequest, ChangeType, ChangeRequestStatus, RiskLevel

CONNECTOR_TO_CHANGE_TYPE: dict[str, str] = {
    "okta":             "rotate_service_account",
    "active_directory": "offboard_user",
    "google_workspace": "offboard_user",
    "github":           "offboard_user",
    "entra_id":         "offboard_user",
    "azure":            "offboard_user",
    "aws":              "key_rotation",
}


def connector_type_to_change_type(connector_type: str) -> str:
    return CONNECTOR_TO_CHANGE_TYPE.get(connector_type, "remote_command")


async def generate_revocation_crs(
    campaign: ReviewCampaign,
    approver_id: uuid.UUID,
    db: AsyncSession,
) -> int:
    """
    For each ReviewEntry with decision='revoke', create a draft ChangeRequest
    and link it back via entry.change_request_id.
    Returns count of CRs created.
    """
    result = await db.execute(
        select(ReviewEntry).where(
            ReviewEntry.campaign_id == campaign.id,
            ReviewEntry.decision == "revoke",
        )
    )
    revoke_entries = result.scalars().all()
    count = 0

    for entry in revoke_entries:
        change_type_str = connector_type_to_change_type(entry.resource_type)
        try:
            ct = ChangeType(change_type_str)
        except ValueError:
            ct = ChangeType.remote_command

        cr = ChangeRequest(
            id=uuid.uuid4(),
            organization_id=campaign.organization_id,
            requester_id=approver_id,
            title=f"Revoke access: {entry.user_email} -> {entry.resource_name}",
            description=(
                f"Generated by access review campaign '{campaign.title}'.\n"
                f"Reviewer decision: revoke {entry.permission_level} access.\n"
                f"Note: {entry.decision_note or 'None'}"
            ),
            change_type=ct,
            target_asset_ids=[str(entry.connector_id)] if entry.connector_id else [],
            desired_outcome={
                "user_email": entry.user_email,
                "resource_name": entry.resource_name,
                "permission_level": entry.permission_level,
                "review_campaign_id": str(campaign.id),
            },
            risk_level=RiskLevel.high if entry.is_privileged else RiskLevel.medium,
            status=ChangeRequestStatus.draft,
            source="access_review",
        )
        db.add(cr)
        await db.flush()

        entry.change_request_id = cr.id
        count += 1

    return count
