from typing import Protocol, runtime_checkable


@runtime_checkable
class SecretBackend(Protocol):
    def encrypt(self, value: str, *, connector_id: str = "") -> str: ...
    def decrypt(self, encrypted: str) -> str: ...
    def encrypt_json(self, data: dict, *, connector_id: str = "") -> str: ...
    def decrypt_json(self, encrypted: str) -> dict: ...
    def delete_secret(self, stored: str) -> None: ...
