from typing import Protocol, runtime_checkable


@runtime_checkable
class SecretBackend(Protocol):
    def encrypt(self, value: str) -> str: ...
    def decrypt(self, encrypted: str) -> str: ...
    def encrypt_json(self, data: dict) -> str: ...
    def decrypt_json(self, encrypted: str) -> dict: ...
