"""add_rotate_secrets_manager_and_jwt_change_types

Revision ID: 184f1eea3cad
Revises: 3e70397d9da4
Create Date: 2026-05-15 03:07:26.891373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '184f1eea3cad'
down_revision: Union[str, None] = '3e70397d9da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_review_schedules')
    op.drop_index('ix_secret_versions_secret_id', table_name='secret_versions')
    op.drop_index('ix_secret_versions_secret_id_status', table_name='secret_versions')
    op.drop_table('secret_versions')
    op.drop_index('ix_compliance_attestations_control_id', table_name='compliance_attestations')
    op.drop_index('ix_compliance_attestations_organization_id', table_name='compliance_attestations')
    op.drop_table('compliance_attestations')
    op.drop_index('ix_notifications_organization_id', table_name='notifications')
    op.drop_index('ix_notifications_recipient_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_drift_alerts_asset_id', table_name='drift_alerts')
    op.drop_index('ix_drift_alerts_organization_id', table_name='drift_alerts')
    op.drop_table('drift_alerts')
    op.drop_table('organization_settings')
    op.drop_index('idx_freeze_windows_active', table_name='change_freeze_windows')
    op.drop_table('change_freeze_windows')
    op.drop_index('idx_compliance_baselines_org', table_name='compliance_baselines')
    op.drop_index('idx_compliance_baselines_scope', table_name='compliance_baselines')
    op.drop_table('compliance_baselines')
    op.drop_index('ix_rp_org_id', table_name='remediation_policies')
    op.drop_table('remediation_policies')
    op.drop_table('agent_registrations')
    op.drop_table('ir_playbook_templates')
    op.drop_index('ix_project_change_requests_project_id', table_name='project_change_requests')
    op.drop_table('project_change_requests')
    op.drop_table('access_reviews')
    op.drop_index('ix_project_phases_project_id', table_name='project_phases')
    op.drop_table('project_phases')
    op.drop_index('idx_forensic_bundles_asset_id', table_name='forensic_bundles')
    op.drop_index('idx_forensic_bundles_collected_at', table_name='forensic_bundles')
    op.drop_table('forensic_bundles')
    op.drop_index('ix_policy_baselines_asset_id', table_name='policy_baselines')
    op.drop_index('ix_policy_baselines_organization_id', table_name='policy_baselines')
    op.drop_table('policy_baselines')
    op.drop_index('ix_maintenance_window_org', table_name='maintenance_window')
    op.drop_table('maintenance_window')
    op.drop_index('ix_rs_org_due', table_name='remediation_slas')
    op.drop_table('remediation_slas')
    op.drop_table('agent_jobs')
    op.drop_index('ix_vf_asset_id', table_name='vulnerability_findings')
    op.drop_index('ix_vf_org_id', table_name='vulnerability_findings')
    op.drop_index('ix_vf_severity', table_name='vulnerability_findings')
    op.drop_index('ix_vf_status', table_name='vulnerability_findings')
    op.drop_table('vulnerability_findings')
    op.drop_index('ix_projects_organization_id', table_name='projects')
    op.drop_table('projects')
    op.alter_column('approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_plans', 'generated_by',
               existing_type=postgresql.ENUM('system', 'ai_mock', 'human', name='plan_generated_by'),
               nullable=False,
               existing_server_default=sa.text("'system'::plan_generated_by"))
    op.alter_column('change_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_requests', 'risk_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='risk_level'),
               nullable=False,
               existing_server_default=sa.text("'medium'::risk_level"))
    op.alter_column('change_requests', 'status',
               existing_type=postgresql.ENUM('draft', 'planned', 'safety_review', 'awaiting_approval', 'approved', 'executing', 'verifying', 'completed', 'failed', 'rolled_back', 'rejected', 'queued_for_maintenance', 'preflight_running', 'preflight_failed', 'batch_running', 'batch_aborted', 'completed_with_errors', name='change_request_status'),
               nullable=False,
               existing_server_default=sa.text("'draft'::change_request_status"))
    op.alter_column('change_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('change_requests_finding_id_fkey', 'change_requests', type_='foreignkey')
    op.drop_constraint('change_requests_ir_template_id_fkey', 'change_requests', type_='foreignkey')
    op.drop_column('change_requests', 'runbook_execution_id')
    op.drop_column('change_requests', 'step_results')
    op.drop_column('change_requests', 'ir_template_id')
    op.drop_column('change_requests', 'output')
    op.drop_column('change_requests', 'incident_response')
    op.drop_column('change_requests', 'step_metadata')
    op.drop_column('change_requests', 'ir_playbook_type')
    op.alter_column('connector_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('connectors', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'error', name='connector_status'),
               nullable=False,
               existing_server_default=sa.text("'active'::connector_status"))
    op.alter_column('connectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_runs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'failed', 'rolling_back', 'rolled_back', name='execution_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::execution_status"))
    op.alter_column('execution_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patch_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_patch_campaigns_org', table_name='patch_campaigns')
    op.create_index(op.f('ix_patch_campaigns_organization_id'), 'patch_campaigns', ['organization_id'], unique=False)
    op.alter_column('review_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_review_campaigns_org_id', table_name='review_campaigns')
    op.drop_index('ix_review_campaigns_status', table_name='review_campaigns')
    op.drop_index('ix_review_entries_campaign_id', table_name='review_entries')
    op.drop_index('ix_review_entries_reviewer_id', table_name='review_entries')
    op.alter_column('runbook_executions', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_runbook_executions_status', table_name='runbook_executions')
    op.alter_column('runbooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('runbooks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_ingests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_ingests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('runbooks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('runbooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_runbook_executions_status', 'runbook_executions', ['status'], unique=False)
    op.alter_column('runbook_executions', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_review_entries_reviewer_id', 'review_entries', ['reviewer_id'], unique=False)
    op.create_index('ix_review_entries_campaign_id', 'review_entries', ['campaign_id'], unique=False)
    op.create_index('ix_review_campaigns_status', 'review_campaigns', ['status'], unique=False)
    op.create_index('ix_review_campaigns_org_id', 'review_campaigns', ['organization_id'], unique=False)
    op.alter_column('review_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_patch_campaigns_organization_id'), table_name='patch_campaigns')
    op.create_index('ix_patch_campaigns_org', 'patch_campaigns', ['organization_id'], unique=False)
    op.alter_column('patch_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_runs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'failed', 'rolling_back', 'rolled_back', name='execution_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::execution_status"))
    op.alter_column('connectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('connectors', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'error', name='connector_status'),
               nullable=True,
               existing_server_default=sa.text("'active'::connector_status"))
    op.alter_column('connector_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('change_requests', sa.Column('ir_playbook_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('incident_response', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('change_requests', sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('ir_template_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('change_requests', sa.Column('step_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('change_requests', sa.Column('runbook_execution_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('change_requests_ir_template_id_fkey', 'change_requests', 'ir_playbook_templates', ['ir_template_id'], ['id'])
    op.create_foreign_key('change_requests_finding_id_fkey', 'change_requests', 'vulnerability_findings', ['finding_id'], ['id'])
    op.alter_column('change_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_requests', 'status',
               existing_type=postgresql.ENUM('draft', 'planned', 'safety_review', 'awaiting_approval', 'approved', 'executing', 'verifying', 'completed', 'failed', 'rolled_back', 'rejected', 'queued_for_maintenance', 'preflight_running', 'preflight_failed', 'batch_running', 'batch_aborted', 'completed_with_errors', name='change_request_status'),
               nullable=True,
               existing_server_default=sa.text("'draft'::change_request_status"))
    op.alter_column('change_requests', 'risk_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='risk_level'),
               nullable=True,
               existing_server_default=sa.text("'medium'::risk_level"))
    op.alter_column('change_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_plans', 'generated_by',
               existing_type=postgresql.ENUM('system', 'ai_mock', 'human', name='plan_generated_by'),
               nullable=True,
               existing_server_default=sa.text("'system'::plan_generated_by"))
    op.alter_column('audit_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('projects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('goal', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'in_progress', 'completed', 'cancelled', name='project_status'), server_default=sa.text("'draft'::project_status"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ai_context', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('template', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('risk_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='projects_created_by_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='projects_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_projects_organization_id', 'projects', ['organization_id'], unique=False)
    op.create_table('vulnerability_findings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('scanner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scanner_finding_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('finding_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cve_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remediation_hint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('affected_package', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('affected_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fixed_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_hostname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('change_request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('accepted_risk_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accepted_risk_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('mitigations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('remediated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('remediated_by_cr_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('mitigated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('mitigated_by_cr_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('patch_available_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='vulnerability_findings_asset_id_fkey'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], name='vulnerability_findings_assigned_to_user_id_fkey'),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name='vulnerability_findings_change_request_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='vulnerability_findings_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vulnerability_findings_pkey'),
    sa.UniqueConstraint('organization_id', 'scanner', 'scanner_finding_id', name='uq_finding_scanner_id'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_vf_status', 'vulnerability_findings', ['status'], unique=False)
    op.create_index('ix_vf_severity', 'vulnerability_findings', ['severity'], unique=False)
    op.create_index('ix_vf_org_id', 'vulnerability_findings', ['organization_id'], unique=False)
    op.create_index('ix_vf_asset_id', 'vulnerability_findings', ['asset_id'], unique=False)
    op.create_table('agent_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_registration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('change_request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('command', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('hmac_signature', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', name='agent_job_status'), server_default=sa.text("'pending'::agent_job_status"), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_registration_id'], ['agent_registrations.id'], name='agent_jobs_agent_registration_id_fkey'),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name='agent_jobs_change_request_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='agent_jobs_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agent_jobs_pkey')
    )
    op.create_table('remediation_slas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sla_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('breached', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('breach_notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('escalated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['vulnerability_findings.id'], name='remediation_slas_finding_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='remediation_slas_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remediation_slas_pkey'),
    sa.UniqueConstraint('finding_id', name='remediation_slas_finding_id_key')
    )
    op.create_index('ix_rs_org_due', 'remediation_slas', ['organization_id', 'due_at'], unique=False)
    op.create_table('maintenance_window',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cron_schedule', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False),
    sa.Column('applies_to_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('enforcement', sa.VARCHAR(length=16), server_default=sa.text("'advisory'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='maintenance_window_pkey')
    )
    op.create_index('ix_maintenance_window_org', 'maintenance_window', ['organization_id'], unique=False)
    op.create_table('policy_baselines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('policy_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('cr_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('observation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='policy_baselines_pkey')
    )
    op.create_index('ix_policy_baselines_organization_id', 'policy_baselines', ['organization_id'], unique=False)
    op.create_index('ix_policy_baselines_asset_id', 'policy_baselines', ['asset_id'], unique=False)
    op.create_table('forensic_bundles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('change_request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('upload_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='forensic_bundles_asset_id_fkey'),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name='forensic_bundles_change_request_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='forensic_bundles_pkey')
    )
    op.create_index('idx_forensic_bundles_collected_at', 'forensic_bundles', ['collected_at'], unique=False)
    op.create_index('idx_forensic_bundles_asset_id', 'forensic_bundles', ['asset_id'], unique=False)
    op.create_table('project_phases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('soak_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('soak_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('soak_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_phases_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='project_phases_pkey')
    )
    op.create_index('ix_project_phases_project_id', 'project_phases', ['project_id'], unique=False)
    op.create_table('access_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='access_reviews_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='access_reviews_pkey')
    )
    op.create_table('project_change_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('change_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sequence_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('depends_on', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name='project_change_requests_change_request_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_change_requests_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_change_requests_pkey')
    )
    op.create_index('ix_project_change_requests_project_id', 'project_change_requests', ['project_id'], unique=False)
    op.create_table('ir_playbook_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('playbook_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('ir_auto_approve', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ir_playbook_templates_pkey'),
    sa.UniqueConstraint('playbook_type', name='ir_playbook_templates_playbook_type_key')
    )
    op.create_table('agent_registrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('machine_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('os_type', postgresql.ENUM('linux', 'windows', name='os_type'), autoincrement=False, nullable=False),
    sa.Column('ip_addresses', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('os_version', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('agent_version', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='agent_registrations_asset_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='agent_registrations_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agent_registrations_pkey'),
    sa.UniqueConstraint('organization_id', 'machine_id', name='uq_agent_registrations_org_machine')
    )
    op.create_table('remediation_policies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('match_scanner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('match_finding_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('match_severity', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('match_resource_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('approval_level', sa.VARCHAR(), server_default=sa.text("'require_approval'::character varying"), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='remediation_policies_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remediation_policies_pkey')
    )
    op.create_index('ix_rp_org_id', 'remediation_policies', ['organization_id'], unique=False)
    op.create_table('compliance_baselines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scope_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scope_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cis_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('os_family', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('history', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), server_default=sa.text("'{}'::jsonb[]"), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('auto_execute', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("scope_type = ANY (ARRAY['asset'::text, 'tag'::text])", name='ck_baseline_scope_type'),
    sa.CheckConstraint('cis_level = ANY (ARRAY[1, 2])', name='ck_baseline_cis_level'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='compliance_baselines_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='compliance_baselines_pkey')
    )
    op.create_index('idx_compliance_baselines_scope', 'compliance_baselines', ['scope_type', 'scope_value'], unique=False)
    op.create_index('idx_compliance_baselines_org', 'compliance_baselines', ['organization_id'], unique=False)
    op.create_table('change_freeze_windows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('emergency_bypass_role', sa.TEXT(), server_default=sa.text("'emergency_bypass'::text"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_freeze_window_dates'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='change_freeze_windows_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='change_freeze_windows_pkey')
    )
    op.create_index('idx_freeze_windows_active', 'change_freeze_windows', ['start_at', 'end_at'], unique=False)
    op.create_table('organization_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('anthropic_api_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('agent_secret_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_providers_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sla_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('escalation_chain', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('escalation_timeout_minutes', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='organization_settings_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='organization_settings_pkey'),
    sa.UniqueConstraint('organization_id', name='organization_settings_organization_id_key')
    )
    op.create_table('drift_alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('policy_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('baseline_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('new_behaviors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='drift_alerts_pkey')
    )
    op.create_index('ix_drift_alerts_organization_id', 'drift_alerts', ['organization_id'], unique=False)
    op.create_index('ix_drift_alerts_asset_id', 'drift_alerts', ['asset_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_recipient_user_id', 'notifications', ['recipient_user_id'], unique=False)
    op.create_index('ix_notifications_organization_id', 'notifications', ['organization_id'], unique=False)
    op.create_table('compliance_attestations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('control_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('attested_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('evidence_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='compliance_attestations_pkey')
    )
    op.create_index('ix_compliance_attestations_organization_id', 'compliance_attestations', ['organization_id'], unique=False)
    op.create_index('ix_compliance_attestations_control_id', 'compliance_attestations', ['control_id'], unique=False)
    op.create_table('secret_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('secret_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ciphertext', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('current', 'superseded', name='secret_version_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='secret_versions_pkey')
    )
    op.create_index('ix_secret_versions_secret_id_status', 'secret_versions', ['secret_id', 'status'], unique=False)
    op.create_index('ix_secret_versions_secret_id', 'secret_versions', ['secret_id'], unique=False)
    op.create_table('access_review_schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('frequency_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=255), server_default=sa.text("'all_users'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reviewer_assignment_rule', sa.VARCHAR(length=100), server_default=sa.text("'direct_manager'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_review_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='access_review_schedules_pkey')
    )
    # ### end Alembic commands ###
