"""create_all_missing_tables

Revision ID: 1d2e3eafddc7
Revises: c862eba68975
Create Date: 2026-05-17 09:58:07.125655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d2e3eafddc7'
down_revision: Union[str, None] = 'c862eba68975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables that may already exist from an earlier branch before recreating
    for _t in [
        'remediation_slas', 'agent_jobs', 'project_phases', 'project_change_requests',
        'projects',
        'forensic_bundles', 'agent_registrations', 'access_reviews', 'change_freeze_windows',
        'remediation_policies', 'compliance_baselines', 'policy_baselines', 'maintenance_window',
        'ir_playbook_templates', 'drift_alerts', 'compliance_attestations', 'access_review_schedules',
    ]:
        op.execute(f"DROP TABLE IF EXISTS {_t} CASCADE")
    op.create_table('access_review_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('reviewer_assignment_rule', sa.String(length=100), nullable=False),
    sa.Column('last_review_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_attestations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('attested_by', sa.UUID(), nullable=False),
    sa.Column('evidence_description', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_attestations_control_id'), 'compliance_attestations', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_attestations_organization_id'), 'compliance_attestations', ['organization_id'], unique=False)
    op.create_table('drift_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('policy_type', sa.String(length=32), nullable=False),
    sa.Column('baseline_id', sa.Uuid(), nullable=False),
    sa.Column('new_behaviors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_alerts_asset_id'), 'drift_alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_drift_alerts_organization_id'), 'drift_alerts', ['organization_id'], unique=False)
    op.create_table('ir_playbook_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playbook_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_parameters', sa.JSON(), nullable=False),
    sa.Column('ir_auto_approve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playbook_type')
    )
    op.create_table('maintenance_window',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_schedule', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('applies_to_tags', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('enforcement', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_window_organization_id'), 'maintenance_window', ['organization_id'], unique=False)
    op.create_table('policy_baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('policy_type', sa.String(length=32), nullable=False),
    sa.Column('cr_id', sa.String(length=64), nullable=True),
    sa.Column('observation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_baselines_asset_id'), 'policy_baselines', ['asset_id'], unique=False)
    op.create_index(op.f('ix_policy_baselines_organization_id'), 'policy_baselines', ['organization_id'], unique=False)
    op.create_table('compliance_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_value', sa.Text(), nullable=False),
    sa.Column('cis_level', sa.Integer(), nullable=False),
    sa.Column('os_family', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_baselines_organization_id'), 'compliance_baselines', ['organization_id'], unique=False)
    op.create_table('remediation_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('match_scanner', sa.String(), nullable=True),
    sa.Column('match_finding_type', sa.String(), nullable=True),
    sa.Column('match_severity', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('match_resource_type', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_params', sa.JSON(), nullable=True),
    sa.Column('approval_level', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_policies_organization_id'), 'remediation_policies', ['organization_id'], unique=False)
    op.create_table('access_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_freeze_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emergency_bypass_role', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os_type', postgresql.ENUM('linux', 'windows', name='os_type', create_type=False), nullable=False),
    sa.Column('ip_addresses', sa.JSON(), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'machine_id', name='uq_agent_registrations_org_machine')
    )
    op.create_table('forensic_bundles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('change_request_id', sa.UUID(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, server_default=sa.text("''")),
    sa.Column('goal', sa.Text(), nullable=False, server_default=sa.text("''")),
    sa.Column('status', sa.String(length=32), nullable=False, server_default=sa.text("'draft'")),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    sa.Column('ai_context', sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    sa.Column('template', sa.String(length=64), nullable=True),
    sa.Column('risk_context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('change_request_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_phases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('soak_hours', sa.Integer(), nullable=False),
    sa.Column('soak_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('soak_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_phases_project_id'), 'project_phases', ['project_id'], unique=False)
    op.create_table('agent_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_registration_id', sa.UUID(), nullable=False),
    sa.Column('change_request_id', sa.UUID(), nullable=True),
    sa.Column('command', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('hmac_signature', sa.String(length=64), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', name='agent_job_status', create_type=False), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_registration_id'], ['agent_registrations.id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_slas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('breach_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['vulnerability_findings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id')
    )
    op.create_index(op.f('ix_remediation_slas_organization_id'), 'remediation_slas', ['organization_id'], unique=False)
    op.alter_column('organization_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Skip projects.status alter — already correct type in DB
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute('DROP INDEX IF EXISTS ix_projects_organization_id')
    op.drop_index('ix_vuln_asset', table_name='vulnerability_findings')
    op.drop_index('ix_vuln_org', table_name='vulnerability_findings')
    op.drop_index('ix_vuln_severity', table_name='vulnerability_findings')
    op.drop_index('ix_vuln_status', table_name='vulnerability_findings')
    op.create_unique_constraint('uq_finding_scanner_id', 'vulnerability_findings', ['organization_id', 'scanner', 'scanner_finding_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_finding_scanner_id', 'vulnerability_findings', type_='unique')
    op.execute('DROP INDEX IF EXISTS ix_vuln_status')
    op.execute('DROP INDEX IF EXISTS ix_vuln_severity')
    op.execute('DROP INDEX IF EXISTS ix_vuln_org')
    op.execute('DROP INDEX IF EXISTS ix_vuln_asset')
    op.create_index('ix_vuln_status', 'vulnerability_findings', ['status'], unique=False)
    op.create_index('ix_vuln_severity', 'vulnerability_findings', ['severity'], unique=False)
    op.create_index('ix_vuln_org', 'vulnerability_findings', ['organization_id'], unique=False)
    op.create_index('ix_vuln_asset', 'vulnerability_findings', ['asset_id'], unique=False)
    op.execute('DROP INDEX IF EXISTS ix_projects_organization_id')
    op.create_index('ix_projects_organization_id', 'projects', ['organization_id'], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('draft', 'in_progress', 'completed', 'cancelled', name='project_status', create_type=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('organization_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_remediation_slas_organization_id'), table_name='remediation_slas')
    op.drop_table('remediation_slas')
    op.drop_table('agent_jobs')
    op.drop_index(op.f('ix_project_phases_project_id'), table_name='project_phases')
    op.drop_table('project_phases')
    op.drop_table('project_change_requests')
    op.drop_table('forensic_bundles')
    op.drop_table('agent_registrations')
    op.drop_table('change_freeze_windows')
    op.drop_table('access_reviews')
    op.drop_index(op.f('ix_remediation_policies_organization_id'), table_name='remediation_policies')
    op.drop_table('remediation_policies')
    op.drop_index(op.f('ix_compliance_baselines_organization_id'), table_name='compliance_baselines')
    op.drop_table('compliance_baselines')
    op.drop_index(op.f('ix_policy_baselines_organization_id'), table_name='policy_baselines')
    op.drop_index(op.f('ix_policy_baselines_asset_id'), table_name='policy_baselines')
    op.drop_table('policy_baselines')
    op.drop_index(op.f('ix_maintenance_window_organization_id'), table_name='maintenance_window')
    op.drop_table('maintenance_window')
    op.drop_table('ir_playbook_templates')
    op.drop_index(op.f('ix_drift_alerts_organization_id'), table_name='drift_alerts')
    op.drop_index(op.f('ix_drift_alerts_asset_id'), table_name='drift_alerts')
    op.drop_table('drift_alerts')
    op.drop_index(op.f('ix_compliance_attestations_organization_id'), table_name='compliance_attestations')
    op.drop_index(op.f('ix_compliance_attestations_control_id'), table_name='compliance_attestations')
    op.drop_table('compliance_attestations')
    op.drop_table('access_review_schedules')
    # ### end Alembic commands ###
