"""add_smoke_test_runs

Revision ID: 99745eb6873e
Revises: 054_merge_branches
Create Date: 2026-05-17 00:24:14.941639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99745eb6873e'
down_revision: Union[str, None] = '054_merge_branches'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smoke_test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runner_instance_id', sa.String(length=50), nullable=True),
    sa.Column('progress_ssm_key', sa.String(length=255), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smoke_test_runs_organization_id'), 'smoke_test_runs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smoke_test_runs_organization_id'), table_name='smoke_test_runs')
    op.drop_table('smoke_test_runs')
    # ### end Alembic commands ###
